name: demo-pic18-build

on:
  push:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    container: "ghcr.io/stone-path-engineering/demo-pic18:main"
    steps:
      - name: Download source
        uses: actions/checkout@v1

      - name: MPLAB Makefiles generation
        run: prjMakefilesGenerator.sh timer-blink.X -mdfp=/opt/mplabx/packs/Microchip/${PACK_FAMILY}/${PACK_VERSION}

      # - name: Build debug
      #   run: make -C timer-blink.X CONF=debug build

      - name: Build release
        run: make -C timer-blink.X CONF=release build
