name: demo-pic18-build

on:
  push:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    container: alexfabre/mplabx-xc8:2.46
    steps:
      - name: Download source
        uses: actions/checkout@v1

      - name: MPLAB Makefiles generation
        run: prjMakefilesGenerator.sh project_name.X

      # - name: Build debug
      #   run: make -C project_name.X CONF=debug build

      - name: Build release
        run: make -C project_name.X CONF=release build
