#name: demo-pic18

#on:
#  push:
#    branches: [ "*" ]
#    # Publish semver tags as releases.
#    tags: [ '*.*' ]
#  pull_request:
#    branches: [ "main" ]

# jobs:
#   build:

#     runs-on: alexfabre/mplabx-xc8

#     steps:
#     - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
#     - uses: actions/upload-artifact@v1
#       with:
#         name: timer-blink
#         path: timer-blink.X/dist/default/production/
