name: demo-pic18-release

permissions:
  write-all
  
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Release:
    runs-on: ubuntu-latest
    container: "ghcr.io/stone-path-engineering/demo-pic18:main"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: MPLAB Makefiles generation
        run: prjMakefilesGenerator.sh timer-blink.X

      - name: Build release
        run: make -C timer-blink.X CONF=release build CFLAGS="-mdfp=/opt/mplabx/packs/Microchip/$PACK_FAMILY/$PACK_VERSION"
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            timer-blink.X/dist/release/production/timer-blink.X.production.elf
            timer-blink.X/dist/release/production/timer-blink.X.production.hex
            LICENSE
            
          # Future files: DFU binaries          
          # timer-blink.X/dist/release/production/timer-blink.X.production.bin