name: demo-pic18-release

on:
  push:
    tags:
      - "v*.*"

jobs:
  Release:
    runs-on: ubuntu-latest
    container: alexfabre/mplabx-xc8:2.46
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: MPLAB Makefiles generation
        run: prjMakefilesGenerator.sh project_name.X
      - name: Build release
        run: make -C project_name.X CONF=release build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            demo-pic18/timer-blink.X/dist/release/timer-blink.X.production.elf
            demo-pic18/timer-blink.X/dist/release/timer-blink.X.production.hex
            demo-pic18/timer-blink.X/dist/release/timer-blink.X.production.map
            LICENSE
